### PR TITLE
Remove unnecessary [models] input of ModelModalComponent

### LINKED ISSUE #27: IndicatorService.getData should handle null and empty string for models param
IndicatorService.getData() cannot handle having null or an empty string passed for the models param. For the Climate API, null is synonymous with "use all models". The service should handle null being passed, and automatically revert to not passing the models param onto the API in that case, rather than attempt to add `models=` to the query string.

### LINKED ISSUE #28: Remove the 'models' Input from ModelModalComponent
The ModelModalComponent queries for the models available based on the input dataset. It shouldn't be necessary to also Input a list of models. 

Additionally, keeping this input around causes issues with downstream projects that shouldn't need to pass an initial list of models, but also can't pass a null initial value due to #27. As a result, defaulting `models` to an empty array when initializing a ModelModalComponent causes this error querying the Climate API:
```
error: ['Dataset LOCA has no data for model(s) ']
```

### PR DESCRIPTION
**Pull request by CloudNiner**
## Overview

Simplifies logic in ModelModalComponent and fixes bug where we unnecessarily made a getData call when opening the modal

Supersedes #31 by including that fix here since it's required for this change to work cleanly

### Demo

A screenshot of the network tab when opening an indicator chart. Note that there are no failing requests with `models=` nor are there the large number of duplicate requests there were before. Any request in this pane marked with `Initiator:other` is an OPTIONS request sent by the Chrome browser and shouldn't be counted as a request made by our code:

screen shot 2018-01-05 at 2 11 38 pm

Associated UI result of the chart load above:

screen shot 2018-01-05 at 2 11 31 pm

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

Testing is no longer straightforward and cannot be done via Lab because it uses an old version of components and requires other updates due to breaking changes. If you'd like to test, message me directly.

If testing, the following should be fixed:
- Far fewer, more consistent requests each time a indicator chart is opened
- No change to ModelModalComponent user-facing behavior
- No Indicator data request when the ModelModalComponent is opened
- No more transient "Dataset LOCA has no models" errors

Closes #27, Closes #28

### CODE REVIEW

File: src/lib/modules/charts/components/model-modal/model-modal.component.ts [hunk 1]
```diff
@@ -43,12 +50,16 @@ export class ModelModalComponent implements OnInit {
         this.getClimateModels();
     }
 
+    ngOnChanges(changes: SimpleChanges) {
```
Comment (fungjj92) [inline src/lib/modules/charts/components/model-modal/model-modal.component.ts]: Why add SimpleChanges?
My understanding is that you use SimpleChanges if you want access to it's properties, but it is not used except by implicit typing here.

File: src/lib/modules/charts/components/model-modal/model-modal.component.ts [hunk 2]
```diff
@@ -93,21 +101,7 @@ export class ModelModalComponent implements OnInit {
...
-                this.models.forEach(projectModel => {
-                    this.climateModels.forEach(model => {
-                        if (projectModel.name === model.name) {
-                           model.selected = projectModel.selected;
-                        }
-                    });
-                });
-            }
-
+            this.selectAllClimateModels();
```
Comment (fungjj92) [inline src/lib/modules/charts/components/model-modal/model-modal.component.ts]: this is because we are removing `project` in lab and always starting with all models?

File: src/lib/modules/charts/components/model-modal/model-modal.component.ts (hunk 1 above)
Comment (CloudNiner) [reply src/lib/modules/charts/components/model-modal/model-modal.component.ts]: Whoops, leftover from previous testing that was reverted. I can remove since its not used.

File: src/lib/modules/charts/components/model-modal/model-modal.component.ts [hunk 3]
```diff
@@ -13,25 +21,24 @@ import { ModalOptions } from 'ngx-bootstrap/modal';
         <ccc-model-modal
```
Comment (fungjj92) [inline src/lib/modules/charts/components/model-modal/model-modal.component.ts]: the first bullet point above needs update, too "Requires input for selected dataset"

**Comment by fungjj92** [comment]
Good after my comments! Ping me to re-review

File: src/lib/modules/charts/components/model-modal/model-modal.component.ts (hunk 2 above)
Comment (CloudNiner) [reply src/lib/modules/charts/components/model-modal/model-modal.component.ts]: Shoot. Not sure we can remove the `[models]` input binding then as we'll no longer be able to update the models list externally like we do in Lab, meaning this change is a feature regression.I should be able to back the changes to remove the input binding, and keep the two non-breaking change fixes. Thoughts?

**Comment by CloudNiner** [comment]
Updated, reverted removal of `[modals]` component input.

File: src/lib/modules/charts/components/model-modal/model-modal.component.ts [hunk 4]
```diff
@@ -102,12 +99,11 @@ export class ModelModalComponent implements OnInit {
                 this.models.forEach(projectModel => {
                     this.climateModels.forEach(model => {
                         if (projectModel.name === model.name) {
-                           model.selected = projectModel.selected;
+                            model.selected = projectModel.selected;
```
Comment (fungjj92) [inline src/lib/modules/charts/components/model-modal/model-modal.component.ts:102]: such a nitpick but it looks like there's an extraneous space

**Review by fungjj92 — APPROVED** [review]
the code looks good. in the interest of time, will test upon the Temperate verson bump PR and adjust accordingly.

File: src/lib/modules/charts/components/model-modal/model-modal.component.ts (hunk 4 above)
Comment (CloudNiner) [reply src/lib/modules/charts/components/model-modal/model-modal.component.ts:102]: Ha, nah, its now properly 4 spaces which is consistent with the rest of the file. It was at three spaces.
